// This file is generated by scripts/generate-canonical-ecosystems.py.
// Do not edit it manually.

use anchor_lang::prelude::*;

use crate::canonical_assets::{BAC_MINT, BBC_MINT, BEC_MINT, BGC_MINT, BLC_MINT, BRC_MINT};

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum CanonicalEcosystem {
    BabyReptile,
    BabyEagle,
    BabyGoat,
    BabyLion,
    BabyBee,
    BabyAgent,
}

pub struct CanonicalEcosystemIdentity {
    pub full_name: &'static str,
    pub ticker: &'static str,
    pub token_address: Pubkey,
    pub mission: &'static str,
}

impl CanonicalEcosystem {
    pub const SPACE: usize = 1;

    pub const ALL: [Self; 6] = [
        Self::BabyReptile,
        Self::BabyEagle,
        Self::BabyGoat,
        Self::BabyLion,
        Self::BabyBee,
        Self::BabyAgent,
    ];

    pub const fn identity(self) -> CanonicalEcosystemIdentity {
        match self {
            Self::BabyReptile => CanonicalEcosystemIdentity {
                full_name: "Baby Reptile Coin",
                ticker: "$BRC",
                token_address: BRC_MINT,
                mission: "This meme coin has come to revolutionize human interactions with the aim of tokenizing all kinds of entertainment and pleasure without any boundaries.",
            },
            Self::BabyEagle => CanonicalEcosystemIdentity {
                full_name: "Baby Eagle Coin",
                ticker: "$BEC",
                token_address: BEC_MINT,
                mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of trades; Import / Export businesses and Logistics without any boundaries.",
            },
            Self::BabyGoat => CanonicalEcosystemIdentity {
                full_name: "Baby Goat Coin",
                ticker: "$BGC",
                token_address: BGC_MINT,
                mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of Intellectual property rights (IPR) & Luxury without any boundaries.",
            },
            Self::BabyLion => CanonicalEcosystemIdentity {
                full_name: "Baby Lion Coin",
                ticker: "$BLC",
                token_address: BLC_MINT,
                mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of manufacturing infrastructures and supply-chains, without any boundaries.",
            },
            Self::BabyBee => CanonicalEcosystemIdentity {
                full_name: "Baby Bee Coin",
                ticker: "$BBC",
                token_address: BBC_MINT,
                mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of Medical services & Health insurance without any boundaries.",
            },
            Self::BabyAgent => CanonicalEcosystemIdentity {
                full_name: "Baby Agent Coin",
                ticker: "$BAC",
                token_address: BAC_MINT,
                mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of Ai services along with IOT and Web3 without any boundaries.",
            },
        }
    }

    pub const fn full_name(self) -> &'static str {
        self.identity().full_name
    }

    pub const fn ticker(self) -> &'static str {
        self.identity().ticker
    }

    pub const fn token_address(self) -> Pubkey {
        self.identity().token_address
    }

    pub const fn mission(self) -> &'static str {
        self.identity().mission
    }

    pub fn from_token_address(token_address: &Pubkey) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|ecosystem| ecosystem.token_address() == *token_address)
    }
}
