#!/usr/bin/env python3

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "specifications/canonical_ecosystems.json"

RUST_OUTPUT = (
    ROOT
    / "protocol/babycowans-protocol/programs/"
    / "babycowans-protocol/src/canonical_ecosystems.rs"
)

TS_OUTPUT = ROOT / "sdk/src/ecosystems/registry.ts"

MINT_CONSTANTS = {
    "BabyReptile": "BRC_MINT",
    "BabyEagle": "BEC_MINT",
    "BabyGoat": "BGC_MINT",
    "BabyLion": "BLC_MINT",
    "BabyBee": "BBC_MINT",
    "BabyAgent": "BAC_MINT",
}


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_registry() -> dict[str, dict[str, str]]:
    registry = json.loads(SOURCE.read_text())

    expected_keys = list(MINT_CONSTANTS)
    if list(registry) != expected_keys:
        raise SystemExit(
            "Canonical ecosystem order or identifiers are invalid."
        )

    required_fields = {
        "fullName",
        "ticker",
        "tokenAddress",
        "mission",
    }

    for key, identity in registry.items():
        if set(identity) != required_fields:
            raise SystemExit(
                f"{key} must contain exactly the four official attributes."
            )

        if not all(
            isinstance(identity[field], str) and identity[field]
            for field in required_fields
        ):
            raise SystemExit(f"{key} contains an empty attribute.")

    token_addresses = [
        identity["tokenAddress"] for identity in registry.values()
    ]

    if len(token_addresses) != len(set(token_addresses)):
        raise SystemExit("Canonical token addresses must be unique.")

    return registry


def generate_rust(registry: dict[str, dict[str, str]]) -> str:
    variants = "\n".join(
        f"    {key}," for key in registry
    )

    all_items = "\n".join(
        f"        Self::{key}," for key in registry
    )

    identity_arms = []

    for key, identity in registry.items():
        identity_arms.append(
            "\n".join(
                [
                    f"            Self::{key} => "
                    "CanonicalEcosystemIdentity {",
                    f"                full_name: "
                    f"{rust_string(identity['fullName'])},",
                    f"                ticker: "
                    f"{rust_string(identity['ticker'])},",
                    f"                token_address: "
                    f"{MINT_CONSTANTS[key]},",
                    f"                mission: "
                    f"{rust_string(identity['mission'])},",
                    "            },",
                ]
            )
        )

    return f"""// This file is generated by scripts/generate-canonical-ecosystems.py.
// Do not edit it manually.

use anchor_lang::prelude::*;

use crate::canonical_assets::{{
    BAC_MINT,
    BBC_MINT,
    BEC_MINT,
    BGC_MINT,
    BLC_MINT,
    BRC_MINT,
}};

#[derive(
    AnchorSerialize,
    AnchorDeserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CanonicalEcosystem {{
{variants}
}}

pub struct CanonicalEcosystemIdentity {{
    pub full_name: &'static str,
    pub ticker: &'static str,
    pub token_address: Pubkey,
    pub mission: &'static str,
}}

impl CanonicalEcosystem {{
    pub const SPACE: usize = 1;

    pub const ALL: [Self; 6] = [
{all_items}
    ];

    pub const fn identity(self) -> CanonicalEcosystemIdentity {{
        match self {{
{chr(10).join(identity_arms)}
        }}
    }}

    pub const fn full_name(self) -> &'static str {{
        self.identity().full_name
    }}

    pub const fn ticker(self) -> &'static str {{
        self.identity().ticker
    }}

    pub const fn token_address(self) -> Pubkey {{
        self.identity().token_address
    }}

    pub const fn mission(self) -> &'static str {{
        self.identity().mission
    }}

    pub fn from_token_address(
        token_address: &Pubkey,
    ) -> Option<Self> {{
        Self::ALL
            .into_iter()
            .find(|ecosystem| {{
                ecosystem.token_address() == *token_address
            }})
    }}
}}
"""


def generate_typescript(
    registry: dict[str, dict[str, str]],
) -> str:
    records = []

    for key, identity in registry.items():
        records.append(
            "\n".join(
                [
                    "    {",
                    f"        ecosystem: "
                    f"CanonicalEcosystem.{key},",
                    f"        fullName: "
                    f"{ts_string(identity['fullName'])},",
                    f"        ticker: "
                    f"{ts_string(identity['ticker'])},",
                    "        tokenAddress: new PublicKey(",
                    f"            "
                    f"{ts_string(identity['tokenAddress'])},",
                    "        ),",
                    f"        mission: "
                    f"{ts_string(identity['mission'])},",
                    "    },",
                ]
            )
        )

    return f"""// This file is generated by scripts/generate-canonical-ecosystems.py.
// Do not edit it manually.

import {{ PublicKey }} from "@solana/web3.js";

import {{
    CanonicalEcosystem,
    CanonicalEcosystemIdentity,
}} from "./types.js";

export const CANONICAL_ECOSYSTEMS:
readonly CanonicalEcosystemIdentity[] = [
{chr(10).join(records)}
] as const;

export function getCanonicalEcosystem(
    ecosystem: CanonicalEcosystem,
): CanonicalEcosystemIdentity {{
    const identity = CANONICAL_ECOSYSTEMS.find(
        (item) => item.ecosystem === ecosystem,
    );

    if (identity === undefined) {{
        throw new Error(
            `Unknown canonical ecosystem: ${{ecosystem}}`,
        );
    }}

    return identity;
}}

export function getCanonicalEcosystemByTokenAddress(
    tokenAddress: PublicKey,
): CanonicalEcosystemIdentity | undefined {{
    return CANONICAL_ECOSYSTEMS.find((item) =>
        item.tokenAddress.equals(tokenAddress),
    );
}}
"""


def main() -> None:
    registry = load_registry()

    RUST_OUTPUT.write_text(generate_rust(registry))
    TS_OUTPUT.write_text(generate_typescript(registry))

    print("Canonical ecosystem registries generated successfully.")


if __name__ == "__main__":
    main()
