// This file is generated by scripts/generate-canonical-ecosystems.py.
// Do not edit it manually.

import { PublicKey } from "@solana/web3.js";

import {
    CanonicalEcosystem,
    CanonicalEcosystemIdentity,
} from "./types.js";

export const CANONICAL_ECOSYSTEMS:
readonly CanonicalEcosystemIdentity[] = [
    {
        ecosystem: CanonicalEcosystem.BabyReptile,
        fullName: "Baby Reptile Coin",
        ticker: "$BRC",
        tokenAddress: new PublicKey(
            "25ZEDgK2R62VRnWbqzfKXire7Gdamkopkx6hqtBwpump",
        ),
        mission: "This meme coin has come to revolutionize human interactions with the aim of tokenizing all kinds of entertainment and pleasure without any boundaries.",
    },
    {
        ecosystem: CanonicalEcosystem.BabyEagle,
        fullName: "Baby Eagle Coin",
        ticker: "$BEC",
        tokenAddress: new PublicKey(
            "BSf9mueWMeHMAJcbmVSY53H8jcQjwVK3oMRkmwnHpump",
        ),
        mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of trades; Import / Export businesses and Logistics without any boundaries.",
    },
    {
        ecosystem: CanonicalEcosystem.BabyGoat,
        fullName: "Baby Goat Coin",
        ticker: "$BGC",
        tokenAddress: new PublicKey(
            "BPCBXkCTYPN3JdcXJojDykmtSvPfykXTLcKnxwopump",
        ),
        mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of Intellectual property rights (IPR) & Luxury without any boundaries.",
    },
    {
        ecosystem: CanonicalEcosystem.BabyLion,
        fullName: "Baby Lion Coin",
        ticker: "$BLC",
        tokenAddress: new PublicKey(
            "GK1twW6K1o3JrnHjxaAk2LGfWkqRnMoBe6Vyydkpump",
        ),
        mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of manufacturing infrastructures and supply-chains, without any boundaries.",
    },
    {
        ecosystem: CanonicalEcosystem.BabyBee,
        fullName: "Baby Bee Coin",
        ticker: "$BBC",
        tokenAddress: new PublicKey(
            "2aso6jnQt3r5sUicejnCFbZupvKaUhezirqVKMjbpump",
        ),
        mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of Medical services & Health insurance without any boundaries.",
    },
    {
        ecosystem: CanonicalEcosystem.BabyAgent,
        fullName: "Baby Agent Coin",
        ticker: "$BAC",
        tokenAddress: new PublicKey(
            "DKBBNADxPhGU4yJihzMUu9fXacibXhYHnQhSo5Wopump",
        ),
        mission: "This meme coin has come to revolutionize Legal interactions with the aim of tokenizing all kinds of Ai services along with IOT and Web3 without any boundaries.",
    },
] as const;

export function getCanonicalEcosystem(
    ecosystem: CanonicalEcosystem,
): CanonicalEcosystemIdentity {
    const identity = CANONICAL_ECOSYSTEMS.find(
        (item) => item.ecosystem === ecosystem,
    );

    if (identity === undefined) {
        throw new Error(
            `Unknown canonical ecosystem: ${ecosystem}`,
        );
    }

    return identity;
}

export function getCanonicalEcosystemByTokenAddress(
    tokenAddress: PublicKey,
): CanonicalEcosystemIdentity | undefined {
    return CANONICAL_ECOSYSTEMS.find((item) =>
        item.tokenAddress.equals(tokenAddress),
    );
}
